### ISSUE TITLE
Set-Output is depricated

### ISSUE THREAD

**Issue by SamBobBarnes** [andstor/file-existence-action#105]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Could this be updated to the new standard?

**Comment by wojsmol** [comment]
cc @andstor

**Comment by andstor** [comment]
Thanks for the heads-up 😊
This should now be resolved in the new major release [v2.0.0](https://github.com/andstor/file-existence-action/releases/tag/v2.0.0).
