### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by raminqaf** [andstor/file-existence-action#143]
@andstor GitHub actions is planning to [deprecate Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The file existence action is still using Node 16. We are getting this warning that the file exists action should be updated to Node 20
```text
Node.js 16 actions are deprecated. 
Please update the following actions to use Node.js 20: andstor/file-existence-action@v2. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Is this action maintained? Are you planning to update it?

**Comment by Gershon-A** [comment]
+1

**Comment by kawon7317** [comment]
Please update it

**Comment by kawon7317** [comment]
I'm getting the same warning from Github actions

**Comment by andstor** [comment]
Thanks for the heads up 😊 

The action is now updated to use Node.js20 as default in [v3.0.0](https://github.com/andstor/file-existence-action/releases/tag/v3.0.0).
