### ISSUE TITLE
`allow_failure` is poorly named

### ISSUE THREAD

**Issue by nterbogt** [andstor/file-existence-action#7]
I would expect if `allow_failure` is false... it would not be allowed to fail finding the files. This is currently not the case... if `allow_failure` is false, the step will succeed if the files are not found.

Alternatively if I set `allow_failure` to true... it fails the step if the files don't exist. That's not allowing a failure.

**Comment by jgwinner** [comment]
Agreed, it's quite confusing. I had to run a few tries until I figured out what's happening.

I wouldn't change the name without a major version bump, but the correct explanation in the Readme would help. 

In either check, the "file exists" step doesn't run if the files don't exist.

**Comment by jgwinner** [comment]
Oh - I suddenly got it. "allow_failure" means of the overall ACTION not of the check for files ...

otherwise, any files that don't exist stop the action. That's sort of what you want, but usually steps fail anyway if there's a missing file.

**Comment by spoyntersmith** [comment]
Whilst it's not a game changer - this could be good to rename in the next version?

I think the description you've got is perfect but 🤯 took me a while

**Comment by andstor** [comment]
Hi!

I have finally changed the `allow_failure` to simply `fail` in the new major [v2.0.0](https://github.com/andstor/file-existence-action/releases/tag/v2.0.0) release.

Hopefully, this will avoid any future confusion (and frustration) 😅
