### ISSUE TITLE
Feature Request: check if file exists, ignore Upper/Lowercase

### ISSUE THREAD

**Issue by joergi** [andstor/file-existence-action#9]
I have a little feature request: is it possible to add a boolean flag, to check if the file exists, but you can ignore upper/lowercase on it?

Because I have an automatic downloader and test, but sometimes people name the files wrong, so they mess-up with upper- or lower case...  but the file is there, that's enough for me.

Is there a possibility to implement this as an optional?

**Comment by joergi** [comment]
(if you don't have the time to implement it yourself, let me know, than I will give it a try...)
p.s. how do you test your script locally?

**Comment by andstor** [comment]
Hi ✋ 
Yes, I think implementing a `ignore_case` flag is a great idea 😄💡
I would appreciate it if you could try and implement it, as I am quite busy at the moment.

The simplest way to test the action is to fork the action, and just try the forked version in a workflow in a repo on GitHub. The functionality of this action is rather simple, so I have not written any tests yet 😅 But **please** feel free to do so!

[This project](https://github.com/nektos/act) seems to enable local testing of actions, but I have not tested it. You can of course also just strip out the action related JavaScript, and run it locally with Node.js. However, do test it in an actual workflow before making a PR.

**Comment by joergi** [comment]
Ok, I will try it on Fr. 16th, as there we have our biweekly "try something out" day at work. Thanks!

**Comment by joergi** [comment]
p.s. can you assign it to me?

**Comment by joergi** [comment]
As promised, I was trying out something.
So: if the folder where the file should exist is all lowercase it works, see this [PR](https://github.com/joergi/file-existence-action/pull/4).
(it's just failing because of this one, I have no idea about this `typescript-eslint/parser.`
```
/home/runner/work/file-existence-action/file-existence-action/src/main.test.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/main.test.ts.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)
```
but the main goal, running `npn test` works, all tests are green.

But:

If a folder to check has something different then lower- (or upper-) case letter,  it's not working, see this [PR](https://github.com/joergi/file-existence-action/pull/3)

And as far as I have seen, there is no way to solve this issue.

so not sure, if you want this "partial working" function in your project.

**Comment by andstor** [comment]
Hi @joergi 👋 

Thanks for the PR. I had to redesign the solution, but I took a lot of inspiration from it (especially the testing) 😄 I have incorporated the ignore case checking with support for glob patterns, and I think I have solved the problem you mention.

So, please check out version [v1.1.0](https://github.com/andstor/file-existence-action/releases/tag/v1.1.0) than now supports glob patterns and an `ignore_case` flag 🥳

Feedback is much appreciated 🙏
